# Generated by Django 4.1.1 on 2022-10-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=40)),
                ('typee', models.CharField(choices=[('text', 'text'), ('feedback', 'feedback')], max_length=10)),
                ('rating', models.CharField(blank=True, choices=[('5', '5'), ('10', '10')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.question')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.sesion')),
            ],
        ),
    ]
